version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: SolveX
    environment:
      POSTGRES_DB: SolveX
      POSTGRES_USER: postgresSolveX
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5435:5432"
    volumes:
      - SolveX_db_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  SolveX_db_data: